wandb_version: 1

activation:
  desc: null
  value: gelu
anneal_strategy:
  desc: null
  value: linear
attn_dropout:
  desc: null
  value: 0.2
attn_mask_type:
  desc: null
  value: strict
batch_size:
  desc: null
  value: 128
context_len:
  desc: null
  value: 20
d_ff:
  desc: null
  value: 256
d_model:
  desc: null
  value: 128
data_mask_method:
  desc: null
  value: both
data_mask_ratio:
  desc: null
  value: 0.2
data_path:
  desc: null
  value: ../../data/SeoulMetro/
default_float:
  desc: null
  value: float32
default_int:
  desc: null
  value: int32
dropout:
  desc: null
  value: 0.2
dset:
  desc: null
  value: seoul
end_minute:
  desc: null
  value: 1441
flow_diff_r:
  desc: null
  value: 0.5
flow_eb:
  desc: null
  value: true
head_dropout:
  desc: null
  value: 0
inflow_file:
  desc: null
  value: in_data.csv
learn_pe:
  desc: null
  value: true
loss:
  desc: null
  value: rmse
max_lr:
  desc: null
  value: 0.001
max_run_time:
  desc: null
  value: 10
n_epochs:
  desc: null
  value: 40
n_heads:
  desc: null
  value: 8
n_layers:
  desc: null
  value: 3
norm:
  desc: null
  value: LayerNorm
num_embeds:
  desc: null
  value:
  - 2
  - 272
  - 7
  - 20
num_patch:
  desc: null
  value: 20
num_target_patch:
  desc: null
  value: 6
outflow_file:
  desc: null
  value: out_data.csv
patch_len:
  desc: null
  value: 1
pe:
  desc: null
  value: zeros
pre_norm:
  desc: null
  value: true
prominence:
  desc: null
  value: 300
seed:
  desc: null
  value: 1
standardization:
  desc: null
  value: zscore
start_minute:
  desc: null
  value: 300
station_eb:
  desc: null
  value: true
store_attn:
  desc: null
  value: true
stride:
  desc: null
  value: 1
subsample:
  desc: null
  value: false
subsample_end:
  desc: null
  value: '2023-01-30'
subsample_start:
  desc: null
  value: '2023-01-01'
t_resolution:
  desc: null
  value: 60T
target_len:
  desc: null
  value: 6
task:
  desc: null
  value: supervised
test_r:
  desc: null
  value: 0.1
time_eb:
  desc: null
  value: true
torch_int:
  desc: null
  value: torch.int32
train_r:
  desc: null
  value: 0.8
val_r:
  desc: null
  value: 0.1
weekday_eb:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.8.1
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684536076.819062
    t:
      1:
      - 1
      - 51
      - 55
      2:
      - 1
      - 51
      - 55
      3:
      - 16
      - 17
      - 23
      4: 3.8.1
      5: 0.15.0
      8:
      - 3
      - 5
